### ISSUE TITLE
Docker-Compose

### ISSUE THREAD

**Issue by gabeanelson** [Supernova3339/anonupload#10]
I didn't want to clutter up your reddit post, but I ran into an issue attempting to spin up the docker-compose.yml. Below is the error.

 ⠿ supernova3339 Error                                                                                           0.7s
Error response from daemon: manifest unknown

**Comment by Supernova3339** [comment]
> I didn't want to clutter up your reddit post, but I ran into an issue attempting to spin up the docker-compose.yml. Below is the error.
> 
> ⠿ supernova3339 Error 0.7s Error response from daemon: manifest unknown

Hey there :wave:
Try changing the  manifest version to 3. Let me know if that works!

**Comment by Supernova3339** [comment]
version 3.3 is the latest version, so I might suggest updating your copy of docker

**Comment by Supernova3339** [comment]
Okay so it is NOT a manifest version, but a docker issue. If you pull the image first, then try to do the docker compose, it should work. If you keep having issues, try the easypanel service, which works out of the box: [https://deploy-preview-164--easypanel-templates.netlify.app/anonfiles](https://deploy-preview-164--easypanel-templates.netlify.app/anonfiles)

**Comment by gabeanelson** [comment]
I tried to pull the image first, but I got the below error. Subsequently, I did a docker login but got the same error again. I might check out easypanel, but I'm pretty locked into docker at this point.

docker pull supernova3339/anonfiles

Using default tag: latest
Error response from daemon: pull access denied for supernova3339/anonfiles, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by Supernova3339** [comment]
> I tried to pull the image first, but I got the below error. Subsequently, I did a docker login but got the same error again. I might check out easypanel, but I'm pretty locked into docker at this point.
> 
> docker pull supernova3339/anonfiles
> 
> Using default tag: latest Error response from daemon: pull access denied for supernova3339/anonfiles, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

do a docker login to ghcr then try again, or do docker pull ghcr.io/supernova3339/anonfiles

**Comment by gabeanelson** [comment]
I figured it out! You don't have a latest tag. I changed it to the below context (added :1) and it worked.

docker pull ghcr.io/supernova3339/anonfiles:1

**Comment by Supernova3339** [comment]
> I figured it out! You don't have a latest tag. I changed it to the below context (added :1) and it worked.
> 
> docker pull ghcr.io/supernova3339/anonfiles:1
> 
> did i forget to add that? whoops! let me know if you have any problems or feedback

also just incase your wondering, easypanel is basically docker with a GUI.
