### ISSUE TITLE
Purchase Code?

### ISSUE THREAD

**Issue by bonxz** [Supernova3339/anonupload#29]
![image](https://user-images.githubusercontent.com/61289944/213764735-d2de0a90-2881-485d-94a7-329c5ea12e32.png)

What should i put in here

**Comment by Supernova3339** [comment]
Hi @bonxz 👋 
Please check the api.php file for the purchase code. This will be removed in 1.01 :)

**Comment by Supernova3339** [comment]
Also... This isn't exactly a bug, so please consider posting on the community forums next time :)
