### ISSUE TITLE
Error 403 forbidden

### ISSUE THREAD

**Issue by betov69** [Supernova3339/anonupload#32]
**Describe the bug**
Error 403 forbidden in admin panel

**To Reproduce**
1. Go to 'www.example.com/admin'
2. Click on 'Files'
3. Scroll down to 'Download or Delete'
4. See error: Error 403 forbidden

**Expected behavior**
Download or delete the file

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Firefox]
 - Version [110]

** Version**
AnonFiles
Version v1.0.0 

**Additional context**
at first you had problems uploading files so apply the following permissions

chown -R www-data:www-data /.../anonfiles/files
chmod 755 /../anonfiles/files

**Comment by Supernova3339** [comment]
Hi there @betov69 :wave: 
Could you please provide any logs from the application? ( console logs )
If I could know where your hosting, that might help too!

**Comment by betov69** [comment]
> 


[log.txt](https://github.com/Supernova3339/anonupload/files/10829314/log.txt)


> Hi there @betov69 👋 Could you please provide any logs from the application? ( console logs ) If I could know where your hosting, that might help too!

Hello, thanks for responding, attached the requested, I host it in Oracle Cloud
[log.txt](https://github.com/Supernova3339/anonupload/files/10829322/log.txt)

**Comment by Supernova3339** [comment]
> > 
> 
> [log.txt](https://github.com/Supernova3339/anonupload/files/10829314/log.txt)
> 
> > Hi there @betov69 👋 Could you please provide any logs from the application? ( console logs ) If I could know where your hosting, that might help too!
> 
> Hello, thanks for responding, attached the requested, I host it in Oracle Cloud [log.txt](https://github.com/Supernova3339/anonupload/files/10829322/log.txt)

Awesome! What instance are you using? AnonUpload may be compatible with all, however it's best to make sure!

**Comment by betov69** [comment]
> > > 
> > 
> > 
> > [log.txt](https://github.com/Supernova3339/anonupload/files/10829314/log.txt)
> > > Hi there @betov69 👋 Could you please provide any logs from the application? ( console logs ) If I could know where your hosting, that might help too!
> > 
> > 
> > Hello, thanks for responding, attached the requested, I host it in Oracle Cloud [log.txt](https://github.com/Supernova3339/anonupload/files/10829322/log.txt)
> 
> Awesome! What instance are you using? AnonUpload may be compatible with all, however it's best to make sure!

Hello, thanks for the follow-up I do not understand very well what you mean is a Linux instance with Ubuntu 22

**Comment by Supernova3339** [comment]
Are you using an ARM based device?

**Comment by betov69** [comment]
Nop, I'm using AMD

![OracleCloud](https://user-images.githubusercontent.com/90874504/221370741-ac94ed61-d0b2-4b97-93b8-99f65b9a396f.png)

**Comment by Supernova3339** [comment]
can  you provide a video and/or console logs?
